### ISSUE TITLE
Code not ready for distribution

### ISSUE THREAD

**Issue by ajkerr0** [tab10/conduction#1]
I'm just being nosy over here.  Disregard me if it doesn't even apply.  If you want this code to be more easily distributed you need to do a few things:
- Needs package structure which means including an `__init__.py` file
- A `setup.py` file in the same directory as the package that contains metadata for package installers.  Looks like you have a `setup.py` already but its being used to 'setup' your actual calculations

**Comment by tab10** [comment]
Thanks for the input. Yeah I don't worry about that stuff until the code is
stable. I'll put something in there that tells others not to use it yet.

On Thursday, June 2, 2016, Alex Kerr <notifications@github.com> wrote:

> I'm just being nosy over here. Disregard me if it doesn't even apply. If
> you want this code to be more easily distributed you need to do a few
> things:
>
>    - Needs package structure which means including an __init__.py file
>    - A setup.py file in the same directory as the package that contains
>    metadata for package installers. Looks like you have a setup.py
>    already but its being used to 'setup' your actual calculations
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tab10/conduction/issues/1>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHR9Sfcsj9QXHwjdCvSZFKCDVs_oC0Jbks5qHvxXgaJpZM4IstIr>
> .
>


-- 
Tim B.
